"""Phase 4 — policy generator: robots.txt block + llms.txt scaffold."""
from __future__ import annotations

import json
import os
import urllib.robotparser
from pathlib import Path
from typing import Literal

PolicyDecision = Literal["block", "allow", "inherit"]

_AGENTS_PATH = Path(
    os.environ.get(
        "AGENTS_PATH",
        str(Path(__file__).parent.parent.parent / "data" / "ai-agents.json"),
    )
)

_CATEGORY_LABELS = {
    "training": "AI Training",
    "search": "AI Search",
    "browsing": "AI Browsing / Agents",
}


def get_agents() -> list[dict]:
    return json.loads(_AGENTS_PATH.read_text())


def get_agents_by_category() -> dict[str, list[dict]]:
    groups: dict[str, list[dict]] = {}
    for a in get_agents():
        cat = a.get("category", "unknown")
        groups.setdefault(cat, []).append(a)
    return groups


def prefill_from_robots(robots_txt: str) -> dict[str, PolicyDecision]:
    """
    Parse a robots.txt string and map known agents to block/allow/inherit.
    Uses urllib.robotparser: if Disallow: / → block, if explicit Allow: / → allow,
    if not mentioned → inherit.
    """
    rp = urllib.robotparser.RobotFileParser()
    rp.parse(robots_txt.splitlines())

    decisions: dict[str, PolicyDecision] = {}
    agents = get_agents()

    for agent in agents:
        token = agent["robots_txt_token"]
        name = agent["name"]
        can_fetch = rp.can_fetch(token, "/")
        mentioned = _is_mentioned(robots_txt, token)

        if mentioned and not can_fetch:
            decisions[name] = "block"
        elif mentioned and can_fetch:
            decisions[name] = "allow"
        else:
            decisions[name] = "inherit"

    return decisions


def _is_mentioned(robots_txt: str, token: str) -> bool:
    token_lower = token.lower()
    for line in robots_txt.splitlines():
        stripped = line.strip().lower()
        if stripped.startswith("user-agent:") and token_lower in stripped:
            return True
    return False


def generate_robots_block(decisions: dict[str, PolicyDecision]) -> str:
    """Generate a robots.txt text block for the given per-agent decisions."""
    agents_by_name = {a["name"]: a for a in get_agents()}
    lines = ["# AI crawler policy — generated by TrueTraffic", "# https://github.com/MarmikPrajapati-ML/truetraffic", ""]

    for name, decision in decisions.items():
        if decision == "inherit":
            continue
        agent = agents_by_name.get(name)
        if not agent:
            continue
        token = agent["robots_txt_token"]
        if decision == "block":
            lines += [f"User-agent: {token}", "Disallow: /", ""]
        else:
            lines += [f"User-agent: {token}", "Allow: /", ""]

    return "\n".join(lines).rstrip() + "\n"


def generate_llms_txt(domain: str, decisions: dict[str, PolicyDecision]) -> str:
    """Generate a /llms.txt scaffold showing AI access policy."""
    blocked = [n for n, d in decisions.items() if d == "block"]
    allowed = [n for n, d in decisions.items() if d == "allow"]
    inherited = [n for n, d in decisions.items() if d == "inherit"]

    lines = [
        f"# {domain or 'Your Site'}",
        "",
        "> [Brief description of what your site is about — edit this line]",
        "",
        "## AI Crawler Policy",
    ]
    if blocked:
        lines += ["", "Blocked from crawling (see robots.txt):"]
        for n in sorted(blocked):
            lines.append(f"- {n}")
    if allowed:
        lines += ["", "Explicitly allowed to crawl:"]
        for n in sorted(allowed):
            lines.append(f"- {n}")
    if inherited:
        lines += ["", "Following wildcard rules (not explicitly set):"]
        for n in sorted(inherited):
            lines.append(f"- {n}")

    lines += [
        "",
        "## Pages",
        f"- [Home](https://{domain or 'yourdomain.com'}/): Main page",
        "",
        "## Terms",
        "See robots.txt for machine-readable crawler policy.",
    ]
    return "\n".join(lines) + "\n"
