"""robots.txt checking logic for TrueTraffic."""
from __future__ import annotations

import json
import os
import urllib.robotparser
from pathlib import Path
from typing import Literal

import httpx

AGENTS_PATH = Path(
    os.environ.get(
        "AGENTS_PATH",
        str(Path(__file__).parent.parent.parent / "data" / "ai-agents.json"),
    )
)
FETCH_TIMEOUT = 3.0

CrawlerStatus = Literal["allowed", "disallowed", "not_mentioned"]


def _load_agents() -> list[dict]:
    return json.loads(AGENTS_PATH.read_text())


def _grade(open_count: int, total: int) -> str:
    """Grade based on how many crawlers have open access (allowed + not_mentioned)."""
    if total == 0:
        return "N/A"
    ratio = open_count / total
    if ratio == 0:
        return "A"
    elif ratio <= 0.25:
        return "B"
    elif ratio <= 0.50:
        return "C"
    elif ratio <= 0.75:
        return "D"
    else:
        return "F"


def _is_explicitly_mentioned(robots_text: str, token: str) -> bool:
    for line in robots_text.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("user-agent:"):
            ua = stripped[len("user-agent:"):].strip()
            if ua.lower() == token.lower():
                return True
    return False


def _check_crawler_in_robots(robots_text: str | None, token: str) -> CrawlerStatus:
    if robots_text is None:
        return "not_mentioned"

    explicitly_mentioned = _is_explicitly_mentioned(robots_text, token)

    rp = urllib.robotparser.RobotFileParser()
    rp.parse(robots_text.splitlines())
    can_crawl = rp.can_fetch(token, "/")

    if explicitly_mentioned:
        return "allowed" if can_crawl else "disallowed"

    # Not explicitly listed — wildcard rules apply.
    # If wildcard blocks all, this crawler is also blocked.
    if not can_crawl:
        return "disallowed"
    return "not_mentioned"


def _build_robots_block(crawler_names: list[str]) -> str:
    if not crawler_names:
        return ""
    lines = ["# Block AI crawlers (generated by TrueTraffic)"]
    for name in crawler_names:
        lines.extend([f"User-agent: {name}", "Disallow: /", ""])
    return "\n".join(lines).rstrip()


async def check_domain(domain: str) -> dict:
    domain = (
        domain.strip()
        .lower()
        .removeprefix("https://")
        .removeprefix("http://")
        .rstrip("/")
    )

    robots_text: str | None = None
    robots_found = False
    llms_found = False

    async with httpx.AsyncClient(timeout=FETCH_TIMEOUT, follow_redirects=True) as client:
        try:
            r = await client.get(f"https://{domain}/robots.txt")
            if r.status_code == 200:
                robots_text = r.text
                robots_found = True
        except httpx.RequestError:
            pass

        try:
            r = await client.get(f"https://{domain}/llms.txt")
            llms_found = r.status_code == 200
        except httpx.RequestError:
            pass

    agents = _load_agents()
    crawlers: list[dict] = []

    for agent in agents:
        status = _check_crawler_in_robots(robots_text, agent["robots_txt_token"])
        crawlers.append(
            {
                "name": agent["name"],
                "vendor": agent["vendor"],
                "category": agent["category"],
                "declared": agent["declared"],
                "status": status,
            }
        )

    disallowed = sum(1 for c in crawlers if c["status"] == "disallowed")
    allowed = sum(1 for c in crawlers if c["status"] == "allowed")
    not_mentioned = sum(1 for c in crawlers if c["status"] == "not_mentioned")
    open_count = allowed + not_mentioned

    to_block = [c["name"] for c in crawlers if c["status"] in ("allowed", "not_mentioned")]

    return {
        "domain": domain,
        "grade": _grade(open_count, len(crawlers)),
        "robots_txt_found": robots_found,
        "llms_txt_found": llms_found,
        "crawlers": crawlers,
        "summary": {
            "allowed": allowed,
            "not_mentioned": not_mentioned,
            "disallowed": disallowed,
            "total": len(crawlers),
        },
        "suggested_robots_block": _build_robots_block(to_block),
    }
